language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk13

services: docker

stages:
  - name: test
  - name: build
    if: branch = master and fork = false and type != pull_request
  - name: deploy
    if: branch = master and fork = false and type != pull_request

jobs:
  include:
    - name: Test
      stage: test
      script: ./gradlew clean test
    - name: Build
      stage: build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull openjdk:13-jdk-alpine
        - ./gradlew clean build
        - ./gradlew jibDockerBuild --image=tuhinchakraborty/covid19-tracker
    - name: Deploy
      stage: deploy
      deploy:
        - provider: heroku
          app:
            master: tracker-covid19
          api_key: $HEROKU_API_KEY

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
